'use strict';
const test=require('node:test'); const assert=require('node:assert/strict');
const fs=require('node:fs'); const path=require('node:path');
const {createCheckoutPos,isMinor}=require('../lib/checkout-pos');
const root=path.join(__dirname,'..'); const sql=n=>fs.readFileSync(path.join(root,'migrations',n),'utf8');
const ID={shop:'11111111-1111-4111-8111-111111111111',appt:'22222222-2222-4222-8222-222222222222',customer:'33333333-3333-4333-8333-333333333333',item:'44444444-4444-4444-8444-444444444444',owner:'55555555-5555-4555-8555-555555555555',checkout:'66666666-6666-4666-8666-666666666666'};
function fixture(){const calls=[]; const client={async query(q,p=[]){calls.push({q,p}); if(q==='BEGIN'||q==='COMMIT'||q==='ROLLBACK'||/^SET LOCAL/.test(q))return{rows:[]}; if(/FROM checkout_transactions/.test(q))return{rows:[]}; if(/FROM appointments a/.test(q))return{rows:[{id:ID.appt,shop_id:ID.shop,customer_id:ID.customer}]}; if(/FROM appointment_items i/.test(q))return{rows:[{id:ID.item,sequence_no:1,service_id:'s',service_name_snapshot:'Service',quote_minor:'8800'}]}; if(/^INSERT INTO checkout_transactions/.test(q))return{rows:[{id:ID.checkout,status:'paid',final_due_minor:8000,paid_minor:8000}]}; if(/^INSERT INTO checkout_(line_items|payments)/.test(q))return{rows:[]}; throw Error(q);},release(){}};return{calls,pool:{connect:async()=>client}};}
const request=(body={})=>({params:{appointmentId:ID.appt},body,ownerAuth:{shopId:ID.shop,ownerAccountId:ID.owner}});
const response=()=>{const r={statusCode:200,status(n){this.statusCode=n;return this},json(v){this.body=v;return this}};return r;};
test('checkout migration chain is staged, tenant-safe and preserves future financial distinctions',()=>{const pre=sql('047_checkout_pos_preflight_readonly.sql'), schema=sql('048_checkout_pos_schema.sql'), verify=sql('049_checkout_pos_verification_readonly.sql'); assert.doesNotMatch(pre,/\b(INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)\b/i); assert.match(schema,/UNIQUE\(shop_id,appointment_id\)/); assert.match(schema,/FOREIGN KEY\(shop_id,appointment_id\)/); assert.match(schema,/cash_collected/); assert.match(schema,/stored_value_bonus/); assert.match(schema,/package_redemption/); assert.match(schema,/checkout_staff_attributions/); assert.doesNotMatch(verify,/\b(INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)\b/i);});
test('minor units reject floats and checkout derives trusted appointment scope',async()=>{assert.equal(isMinor(1000),true);assert.equal(isMinor(1.1),false); const f=fixture(),h=createCheckoutPos({pool:f.pool}).create,r=response();await h(request({idempotencyKey:'a'.repeat(16),items:[{appointmentItemId:ID.item,actualPriceMinor:8800,discountMinor:800}],payments:[{method:'cash',valueKind:'cash_collected',amountMinor:8000,cashCollectedMinor:8000}]}),r);assert.equal(r.statusCode,201);assert.equal(f.calls.some(x=>/shop_id=\$2/.test(x.q)&&/FROM appointments/.test(x.q)),true);assert.equal(f.calls.some(x=>/INSERT INTO checkout_transactions/.test(x.q)),true);});
test('checkout rejects floating money, forged item sets, bonus cash and overpayment before writes',async()=>{for(const body of [{idempotencyKey:'b'.repeat(16),items:[{appointmentItemId:ID.item,actualPriceMinor:1.2}]},{idempotencyKey:'c'.repeat(16),items:[{appointmentItemId:'forged'}]},{idempotencyKey:'d'.repeat(16),payments:[{method:'other',valueKind:'stored_value_bonus',amountMinor:1,cashCollectedMinor:1}]},{idempotencyKey:'e'.repeat(16),payments:[{method:'cash',valueKind:'cash_collected',amountMinor:9999,cashCollectedMinor:9999}] }]){const f=fixture(),r=response();await createCheckoutPos({pool:f.pool}).create(request(body),r);assert.notEqual(r.statusCode,201);assert.equal(f.calls.some(x=>/^INSERT INTO checkout_transactions/.test(x.q)),false);}});
