'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn,spawnSync}=require('node:child_process'); const {Client}=require('pg'); const root=path.join(__dirname,'..'),bin=process.env.PG17_BIN||'/opt/homebrew/opt/postgresql@17/bin',sql=n=>fs.readFileSync(path.join(root,'migrations',n),'utf8');
async function ready(c,p,stderr){let last;for(let i=0;i<50;i+=1){if(p.exitCode!==null||p.signalCode!==null)throw new Error(`postgres exited: ${stderr()}`);const db=new Client(c);try{await db.connect();return db}catch(e){last=e;await db.end().catch(()=>{});await new Promise(r=>setTimeout(r,100))}}throw last}
const query=`SELECT EXISTS(SELECT 1 FROM appointments previous WHERE previous.shop_id=current.shop_id AND previous.recipient_customer_id=current.recipient_customer_id AND previous.status IN ('arrived','in_service','completed') AND previous.start_at<current.start_at AND previous.id<>current.id) AS is_returning_customer FROM appointments current WHERE current.id=$1`;
test('returning rule and 078-080 migration chain execute on PostgreSQL', {timeout:120000}, async t=>{
 if(!fs.existsSync(path.join(bin,'initdb')))return t.skip('PostgreSQL 17 unavailable');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'gg-returning-')),data=path.join(temp,'data'),socket=path.join(temp,'socket'),port=58700+Math.floor(Math.random()*100);fs.mkdirSync(socket);const init=spawnSync(path.join(bin,'initdb'),['-D',data,'-A','trust','--no-locale'],{encoding:'utf8'});assert.equal(init.status,0,init.stderr);let stderr='';const pg=spawn(path.join(bin,'postgres'),['-D',data,'-k',socket,'-p',String(port)],{stdio:['ignore','ignore','pipe']});pg.stderr.on('data',x=>{stderr+=x});const exited=new Promise(r=>pg.once('exit',r));let db;
 try{db=await ready({host:socket,port,database:'postgres',user:os.userInfo().username},pg,()=>stderr);await db.query('CREATE TABLE appointments(id uuid PRIMARY KEY,shop_id uuid NOT NULL,location_id uuid NOT NULL,recipient_customer_id uuid NOT NULL,start_at timestamptz NOT NULL,status text NOT NULL)');for(const n of ['078_returning_customer_index_preflight_readonly.sql','079_returning_customer_index_schema.sql','080_returning_customer_index_verification_readonly.sql'])await db.query(sql(n));const ix=(await db.query("SELECT i.indisvalid,i.indisready,pg_get_indexdef(i.indexrelid) d,pg_get_expr(i.indpred,i.indrelid) p FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid WHERE c.relname='appointments_returning_customer_lookup_idx'")).rows[0];assert.equal(ix.indisvalid,true);assert.equal(ix.indisready,true);assert.match(ix.d,/\(shop_id, recipient_customer_id, start_at, id\)/);assert.match(ix.p,/arrived.*in_service.*completed/);
 const A='11111111-1111-4111-8111-111111111111',B='11111111-1111-4111-8111-222222222222',R='22222222-2222-4222-8222-111111111111',O='22222222-2222-4222-8222-222222222222';let n=0;const add=async(shop,r,start,status,loc='33333333-3333-4333-8333-111111111111')=>{const id=`aaaaaaaa-aaaa-4aaa-8aaa-${String(++n).padStart(12,'0')}`;await db.query('INSERT INTO appointments VALUES($1,$2,$3,$4,$5,$6)',[id,shop,loc,r,start,status]);return id};const yes=id=>db.query(query,[id]).then(x=>x.rows[0].is_returning_customer);
 assert.equal(await yes(await add(A,O,'2026-01-01T10:00Z','pending')),false);for(const status of ['pending','confirmed','cancelled','no_show']){await add(A,R,`2026-01-02T${String(n%10).padStart(2,'0')}:00Z`,status);assert.equal(await yes(await add(A,R,'2026-01-03T10:00Z','pending')),false,status)}for(const status of ['arrived','in_service','completed']){await add(A,R,`2026-02-0${n%8+1}T10:00Z`,status);assert.equal(await yes(await add(A,R,'2026-02-09T10:00Z','pending')),true,status)}
 const X='22222222-2222-4222-8222-333333333333';await add(A,X,'2026-03-01T14:00Z','completed');assert.equal(await yes(await add(A,X,'2026-03-01T10:00Z','pending')),false);await add(A,O,'2026-03-02T10:00Z','completed');assert.equal(await yes(await add(A,O,'2026-03-02T10:00Z','pending')),false);await add(A,X,'2026-03-03T10:00Z','completed','44444444-4444-4444-8444-444444444444');assert.equal(await yes(await add(A,X,'2026-03-03T14:00Z','pending','55555555-5555-4555-8555-555555555555')),true);assert.equal(await yes(await add(B,X,'2026-03-03T14:00Z','pending')),false);await db.query(sql('rollback/079_returning_customer_index_rollback.sql'));assert.equal((await db.query("SELECT to_regclass('public.appointments_returning_customer_lookup_idx') i")).rows[0].i,null);assert.equal((await db.query('SELECT count(*) FROM appointments')).rows[0].count,String(n));
 }finally{if(db)await db.end().catch(()=>{});if(pg.exitCode===null&&pg.signalCode===null)pg.kill('SIGTERM');await exited;fs.rmSync(temp,{recursive:true,force:true})}
});
