'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const { spawn, spawnSync } = require('node:child_process'); const { Client } = require('pg');
const root = path.join(__dirname, '..'); const bin = process.env.PG17_BIN || '/opt/homebrew/opt/postgresql@17/bin'; const sql = n => fs.readFileSync(path.join(root, 'migrations', n), 'utf8');
async function connect(c, p) { let e; for (let i=0;i<50;i++) { if (p.exitCode !== null) throw new Error('postgres exited'); const db=new Client(c); try { await db.connect(); return db; } catch(x) { e=x; await db.end().catch(()=>{}); await new Promise(r=>setTimeout(r,100)); } } throw e; }
test('returning-customer SQL and index migration run on PostgreSQL', { timeout: 120000 }, async t => {
 if (!fs.existsSync(path.join(bin,'initdb'))) return t.skip('PostgreSQL 17 unavailable'); const temp=fs.mkdtempSync(path.join(os.tmpdir(),'gg-returning-')); const data=path.join(temp,'data'), socket=path.join(temp,'socket'), port=58700+Math.floor(Math.random()*100); fs.mkdirSync(socket); const init=spawnSync(path.join(bin,'initdb'),['-D',data,'-A','trust','--no-locale'],{encoding:'utf8'}); assert.equal(init.status,0,init.stderr); const pg=spawn(path.join(bin,'postgres'),['-D',data,'-k',socket,'-p',String(port)]); const pgExit=new Promise(resolve=>pg.once('exit',resolve)); let db;
 try { db=await connect({host:socket,port,database:'postgres',user:os.userInfo().username},pg); await db.query('CREATE TABLE appointments(id uuid PRIMARY KEY,shop_id uuid NOT NULL,location_id uuid,recipient_customer_id uuid,start_at timestamptz,status text)'); await db.query(sql('078_returning_customer_index_preflight_readonly.sql')); await db.query(sql('079_returning_customer_index_schema.sql')); await db.query(sql('080_returning_customer_index_verification_readonly.sql'));
 const s='11111111-1111-4111-8111-111111111111', r='22222222-2222-4222-8222-222222222222', other='33333333-3333-4333-8333-333333333333'; await db.query("INSERT INTO appointments VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-000000000001',$1,'44444444-4444-4444-8444-444444444444',$2,'2026-01-01T02:00Z','arrived'),('aaaaaaaa-aaaa-4aaa-8aaa-000000000002',$1,'55555555-5555-4555-8555-555555555555',$2,'2026-01-01T06:00Z','pending'),('aaaaaaaa-aaaa-4aaa-8aaa-000000000003',$1,NULL,$3,'2026-01-01T01:00Z','completed')",[s,r,other]);
 const q=`SELECT EXISTS(SELECT 1 FROM appointments previous WHERE previous.shop_id=current.shop_id AND previous.recipient_customer_id=current.recipient_customer_id AND previous.status IN ('arrived','in_service','completed') AND previous.start_at<current.start_at AND previous.id<>current.id) AS returning FROM appointments current WHERE current.id='aaaaaaaa-aaaa-4aaa-8aaa-000000000002'`; assert.equal((await db.query(q)).rows[0].returning,true); await db.query(sql('rollback/079_returning_customer_index_rollback.sql')); assert.equal((await db.query("SELECT to_regclass('public.appointments_returning_customer_lookup_idx') AS i")).rows[0].i,null); } finally { if(db) await db.end().catch(()=>{}); if(pg.exitCode===null) pg.kill('SIGTERM'); await pgExit; fs.rmSync(temp,{recursive:true,force:true}); }
});
