'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const path=require('node:path');
const {validateOwnerServiceCategoryFields,resolveCategoryName}=require('../lib/owner-service-category-management');
const root=path.resolve(__dirname,'..'); const server=fs.readFileSync(path.join(root,'server.js'),'utf8'); const ui=fs.readFileSync(path.join(root,'public/admin-self-service.js'),'utf8'); const html=fs.readFileSync(path.join(root,'public/admin.html'),'utf8');
const sql=n=>fs.readFileSync(path.join(root,'migrations',n),'utf8');

test('category input supports bilingual names and normalizes whitespace',()=>{assert.deepEqual(validateOwnerServiceCategoryFields({nameZh:' 美发 ',nameEn:' Hair ',sortOrder:2,isActive:true},false).values,{nameZh:'美发',nameEn:'Hair',sortOrder:2,isActive:true});});
test('blank translations and unknown tenant fields fail closed',()=>{assert.ok(validateOwnerServiceCategoryFields({nameZh:' '},false).error);assert.ok(validateOwnerServiceCategoryFields({nameEn:'Hair',shopId:'x'},false).error);});
test('category locale fallback is requested then en then zh-CN then canonical',()=>{const c={nameZh:'美发',nameEn:'Hair',canonicalName:'Legacy'};assert.equal(resolveCategoryName(c,'zh-SG'),'美发');assert.equal(resolveCategoryName(c,'en'),'Hair');assert.equal(resolveCategoryName({...c,nameZh:null},'zh-CN'),'Hair');assert.equal(resolveCategoryName({canonicalName:'Legacy'},'en'),'Legacy');});
test('owner category routes enforce read and write role policy',()=>{assert.match(server,/service-categories', requireOwnerAuth, requireOwnerRole\(\['owner', 'manager', 'admin'\]\)/);assert.match(server,/service-categories', requireOwnerAuth, requireOwnerRole\(\['owner', 'manager'\]\)/);assert.doesNotMatch(server,/app\.delete\([^\n]*service-categories/i);});
test('all category and service category queries use authenticated shop',()=>{assert.match(server,/assertOwnerServiceCategory\(client, req\.ownerAuth\.shopId/);assert.doesNotMatch(ui,/\bshopId\b|\bshop_id\b|\btenantId\b/);});
test('service category link permits null and rejects invalid UUID',()=>{assert.equal(/body\.categoryId !== null && !isUuid/.test(server),true);assert.match(server,/category_id/);});
test('owner UI provides dynamic category management and real selector',()=>{assert.match(html,/id="categoriesList"/);assert.match(html,/id="serviceCategoryId"/);assert.doesNotMatch(html,/id="serviceCategory"/);assert.match(ui,/\/api\/owner\/service-categories/);});
test('owner UI requires category only for newly created formal services',()=>{assert.match(ui,/!state\.editingServiceId && !categoryId/);assert.match(ui,/categoryId: categoryId \|\| null/);});
test('schema is tenant safe and preserves legacy category text',()=>{const s=sql('019_service_categories_schema.sql');assert.match(s,/FOREIGN KEY\(shop_id,category_id\).*service_categories\(shop_id,id\) ON DELETE RESTRICT/s);assert.match(s,/ALTER TABLE services ADD COLUMN category_id UUID NULL/);assert.doesNotMatch(s,/DROP COLUMN\s+category/i);});
test('legacy backfill is exact tenant-safe and does not guess null categories',()=>{const s=sql('020_service_categories_legacy_backfill.sql');assert.match(s,/s\.category IS NOT NULL/);assert.match(s,/c\.shop_id=s\.shop_id/);assert.match(s,/c\.canonical_name=btrim\(s\.category\)/);assert.doesNotMatch(s,/service_category_translations/);});
test('migration sequence has readonly guards and no appointment snapshots',()=>{assert.match(sql('018_service_categories_preflight_readonly.sql'),/BEGIN TRANSACTION READ ONLY/);assert.match(sql('021_service_categories_verification_readonly.sql'),/BEGIN TRANSACTION READ ONLY/);for(const n of ['019_service_categories_schema.sql','020_service_categories_legacy_backfill.sql']){assert.match(sql(n),/lock_timeout='5s'/);assert.match(sql(n),/statement_timeout='30s'/);}assert.doesNotMatch([server,ui,html,sql('019_service_categories_schema.sql'),sql('020_service_categories_legacy_backfill.sql')].join('\n'),/category_snapshot/);});
