'use strict';
process.env.ADMIN_PASSWORD='local-test-admin-password';
const test=require('node:test');
const assert=require('node:assert/strict');
const {app}=require('../server');
const ID={shop:'11111111-1111-4111-8111-111111111111',otherShop:'22222222-2222-4222-8222-222222222222',staff:'33333333-3333-4333-8333-333333333333',otherStaff:'44444444-4444-4444-8444-444444444444',account:'55555555-5555-4555-8555-555555555555',location:'66666666-6666-4666-8666-666666666666',appointment:'77777777-7777-4777-8777-777777777777'};
function fixture({permission=true,own=true,shop=ID.shop,status='pending',historyFailure=false}={}) {
 const state={status,items:[status],history:[],rolledBack:false};
 const client={async query(sql,p=[]){const s=sql.trim();if(['BEGIN','COMMIT'].includes(s)||/^SET LOCAL/.test(s))return{rows:[]};if(s==='ROLLBACK'){state.rolledBack=true;return{rows:[]};}if(/FROM appointments a WHERE/.test(s))return{rows:own&&p[1]===shop&&p[2]===ID.staff?[{id:ID.appointment,shop_id:shop,location_id:ID.location,service_id:ID.staff,staff_id:ID.staff,start_at:'2030-01-01T10:00:00Z',end_at:'2030-01-01T11:00:00Z',status:state.status,cancelled_at:null,service_completed_at:null,updated_at:'2030-01-01T00:00:00Z'}]:[]};if(/^WITH parent AS/.test(s))return{rows:[{item_count:1,assignment_count:1,structure_valid:true}]};if(/^SELECT id\s+FROM appointment_items/.test(s)||/^SELECT assignment\.id/.test(s))return{rows:[{id:'item'}]};if(/^UPDATE appointments/.test(s)){state.status=p[0];return{rows:[{id:ID.appointment,status:state.status,start_at:'2030-01-01T10:00:00Z',end_at:'2030-01-01T11:00:00Z'}]};}if(/^UPDATE appointment_items/.test(s)){state.items=[p[3]];return{rows:[{id:'item'}]};}if(/^INSERT INTO appointment_status_history/.test(s)){if(historyFailure)throw new Error('history failure');state.history.push({shop:p[0],from:p[2],to:p[3],operatorType:p[4],operatorId:p[5],source:p[6]});return{rows:[]};}throw Error('Unexpected '+s);},release(){}};
 const pool={async query(sql){if(/FROM staff_sessions/.test(sql))return{rows:[{staff_account_id:ID.account,shop_id:shop,staff_id:ID.staff,location_id:ID.location,can_update_own_appointment_status:permission,can_view_customer_history:false,can_view_service_notes:false,can_view_own_sales:false,can_view_own_commission:false,can_view_full_customer_phone:false,can_move_own_appointments:false}]};throw Error('Unexpected auth '+sql);},async connect(){return client;}};return{pool,state};
}
async function call(f,body,cookie=true){app.locals.bookingPool=f.pool;const srv=app.listen(0,'127.0.0.1');await new Promise(r=>srv.once('listening',r));try{const base=`http://127.0.0.1:${srv.address().port}`;const r=await fetch(`${base}/api/staff/appointments/${ID.appointment}/status`,{method:'PATCH',headers:{'Content-Type':'application/json',Origin:base,...(cookie?{Cookie:'gg_beauty_staff_session=x'}:{})},body:JSON.stringify(body)});return{status:r.status,json:await r.json()};}finally{await new Promise(r=>srv.close(r));}}
test('staff status endpoint auth, permission, ownership and lifecycle',async()=>{let f=fixture();assert.equal((await call(f,{status:'confirmed'},false)).status,401);f=fixture({permission:false});assert.equal((await call(f,{status:'confirmed'})).status,403);f=fixture({own:false});assert.equal((await call(f,{status:'confirmed'})).status,404);f=fixture();for(const to of ['confirmed','arrived','in_service','completed'])assert.equal((await call(f,{status:to})).status,200);assert.deepEqual(f.state.history.map(x=>x.to),['confirmed','arrived','in_service','completed']);assert.equal((await call(f,{status:'completed'})).status,200);assert.equal(f.state.history.length,4);assert.deepEqual(f.state.history[0],{shop:ID.shop,from:'pending',to:'confirmed',operatorType:'staff',operatorId:ID.account,source:'staff_portal'});});
test('staff status endpoint terminal and alternate transitions fail closed',async()=>{for(const [from,to] of [['pending','arrived'],['confirmed','completed'],['completed','pending']]){const f=fixture({status:from});assert.equal((await call(f,{status:to})).status,409);}for(const to of ['no_show','cancelled']){const f=fixture({status:'confirmed'});assert.equal((await call(f,{status:to})).status,200);}});
test('staff status history failure rolls back',async()=>{const f=fixture({historyFailure:true});assert.equal((await call(f,{status:'confirmed'})).status,500);assert.equal(f.state.rolledBack,true);});
