//♂==================================================
//♂美容养生预约系统♂-♂纯净版
//♂==================================================
const♂express♂=♂require('express');
const♂app♂=♂express();
app.use(express.json());
♂
const♂CONFIG♂=♂{
♂♂shopName:♂"GG-Beauty",
♂♂currency:♂"S$",
♂♂validUntil:♂"2026-09-19",
♂♂adminPassword:♂"123456",
♂♂services:♂[
♂♂♂♂{♂id:101,♂name:♂"养生♂-♂肩颈舒缓护理",♂duration:♂60♂},
♂♂♂♂{♂id:102,♂name:♂"养生♂-♂身体舒缓护理",♂duration:♂60♂},
♂♂♂♂{♂id:103,♂name:♂"养生♂-♂经络护理",♂duration:♂60♂},
♂♂♂♂{♂id:104,♂name:♂"养生♂-♂淋巴护理",♂duration:♂60♂},
♂♂♂♂{♂id:105,♂name:♂"养生♂-♂精油身体护理",♂duration:♂60♂},
♂♂♂♂{♂id:106,♂name:♂"养生♂-♂腹部护理",♂duration:♂45♂},
♂♂♂♂{♂id:107,♂name:♂"养生♂-♂背部护理",♂duration:♂45♂},
♂♂♂♂{♂id:201,♂name:♂"面部♂-♂基础面部护理",♂duration:♂60♂},
♂♂♂♂{♂id:202,♂name:♂"面部♂-♂深层清洁",♂duration:♂60♂},
♂♂♂♂{♂id:203,♂name:♂"面部♂-♂补水护理",♂duration:♂60♂},
♂♂♂♂{♂id:204,♂name:♂"面部♂-♂面部淋巴护理",♂duration:♂60♂},
♂♂♂♂{♂id:205,♂name:♂"面部♂-♂面部塑形护理",♂duration:♂60♂},
♂♂♂♂{♂id:206,♂name:♂"面部♂-♂提拉紧致护理",♂duration:♂75♂},
♂♂♂♂{♂id:207,♂name:♂"面部♂-♂小V脸护理",♂duration:♂75♂},
♂♂♂♂{♂id:301,♂name:♂"塑形♂-♂腹部塑形",♂duration:♂60♂},
♂♂♂♂{♂id:302,♂name:♂"塑形♂-♂腰腹护理",♂duration:♂60♂},
♂♂♂♂{♂id:303,♂name:♂"塑形♂-♂腿部塑形",♂duration:♂60♂},
♂♂♂♂{♂id:304,♂name:♂"塑形♂-♂身体紧致护理",♂duration:♂75♂},
♂♂♂♂{♂id:305,♂name:♂"塑形♂-♂全身塑形护理",♂duration:♂90♂},
♂♂♂♂{♂id:306,♂name:♂"塑形♂-♂局部塑形护理",♂duration:♂60♂}
♂♂],
♂♂staff:♂["Lily",♂"Coco",♂"Mia"],
♂♂businessHours:♂{♂start:♂"10:00",♂end:♂"20:30"♂}
};
♂
let♂bookings♂=♂[];
♂
app.get('/api/config',♂(req,♂res)♂=>♂res.json({♂success:♂true,♂data:♂CONFIG♂}));
app.get('/api/bookings',♂(req,♂res)♂=>♂res.json({♂success:♂true,♂data:♂bookings♂}));
♂
app.post('/api/new',♂(req,♂res)♂=>♂{
♂♂const♂b♂=♂{♂id:♂Date.now(),♂..req.body,♂time:♂new♂Date().toLocaleString('zh-SG')♂};
♂♂bookings.unshift(b);
♂♂res.json({♂success:♂true,♂message:♂'Booking♂successful!'♂});
});
♂
app.post('/api/admin/login',♂(req,♂res)♂=>♂{
♂♂if♂(req.body.password♂===♂CONFIG.adminPassword)♂res.json({♂success:♂true♂});
♂♂else♂res.status(401).json({♂success:♂false,♂message:♂'Wrong♂password'♂});
});
♂
app.post('/api/admin/update-status',♂(req,♂res)♂=>♂{
♂♂const♂item♂=♂bookings.find(b♂=>♂b.id♂===♂req.body.id);
♂♂if♂(item)♂item.status♂=♂req.body.status;
♂♂res.json({♂success:♂true♂});
});
♂
//♂前端预约页面
app.get('/',♂(req,♂res)♂=>♂{
♂♂//♂原始前端♂HTML/JavaScript♂代码按用户提供版本保留
♂♂//♂（此处为避免♂PDF♂排版过宽，完整源码继续收录于本♂PDF♂后续页面）
});
♂
//♂管理后台
app.get('/admin.html',♂(req,♂res)♂=>♂{
♂♂//♂原始管理后台♂HTML/JavaScript♂代码按用户提供版本保留
});
♂
const♂PORT♂=♂process.env.PORT♂||♂3000;
app.listen(PORT,♂()♂=>♂{
♂♂console.log('〒♂Running♂on♂port♂'♂+♂PORT);
});
