BEGIN TRANSACTION READ ONLY;
DO $$ DECLARE bad BIGINT; BEGIN
 IF to_regclass('public.service_categories') IS NULL OR to_regclass('public.service_category_translations') IS NULL THEN RAISE EXCEPTION 'category tables missing'; END IF;
 IF (SELECT count(*) FROM information_schema.columns WHERE table_schema='public' AND table_name='service_categories')<>8 OR EXISTS(SELECT 1 FROM (VALUES ('id','uuid','NO'),('shop_id','uuid','NO'),('canonical_name','text','NO'),('icon_key','text','YES'),('sort_order','integer','NO'),('is_active','boolean','NO'),('created_at','timestamp with time zone','NO'),('updated_at','timestamp with time zone','NO')) e(name,type,nullable) LEFT JOIN information_schema.columns c ON c.table_schema='public' AND c.table_name='service_categories' AND c.column_name=e.name WHERE c.column_name IS NULL OR c.data_type<>e.type OR c.is_nullable<>e.nullable) THEN RAISE EXCEPTION 'service_categories columns drift'; END IF;
 IF (SELECT count(*) FROM information_schema.columns WHERE table_schema='public' AND table_name='service_category_translations')<>7 OR EXISTS(SELECT 1 FROM (VALUES ('id','uuid','NO'),('shop_id','uuid','NO'),('category_id','uuid','NO'),('locale','text','NO'),('name','text','NO'),('created_at','timestamp with time zone','NO'),('updated_at','timestamp with time zone','NO')) e(name,type,nullable) LEFT JOIN information_schema.columns c ON c.table_schema='public' AND c.table_name='service_category_translations' AND c.column_name=e.name WHERE c.column_name IS NULL OR c.data_type<>e.type OR c.is_nullable<>e.nullable) THEN RAISE EXCEPTION 'service_category_translations columns drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='services' AND column_name='category' AND data_type='text') THEN RAISE EXCEPTION 'legacy services.category missing'; END IF;
 IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='services' AND column_name='category_id' AND data_type='uuid' AND is_nullable='YES') THEN RAISE EXCEPTION 'services.category_id drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.service_categories'::regclass AND contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)') THEN RAISE EXCEPTION 'category primary key drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.service_categories'::regclass AND contype='u' AND pg_get_constraintdef(oid)='UNIQUE (shop_id, id)') THEN RAISE EXCEPTION 'category composite unique drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.service_categories'::regclass AND contype='u' AND pg_get_constraintdef(oid)='UNIQUE (shop_id, canonical_name)') THEN RAISE EXCEPTION 'category canonical unique drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.service_categories'::regclass AND contype='f' AND confrelid='public.shops'::regclass AND confdeltype='r' AND pg_get_constraintdef(oid)='FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE RESTRICT') THEN RAISE EXCEPTION 'category shop FK drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.service_category_translations'::regclass AND contype='p' AND pg_get_constraintdef(oid)='PRIMARY KEY (id)') THEN RAISE EXCEPTION 'translation primary key drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.service_category_translations'::regclass AND contype='u' AND pg_get_constraintdef(oid)='UNIQUE (shop_id, category_id, locale)') THEN RAISE EXCEPTION 'translation unique drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.service_category_translations'::regclass AND contype='f' AND confrelid='public.service_categories'::regclass AND confdeltype='r' AND pg_get_constraintdef(oid)='FOREIGN KEY (shop_id, category_id) REFERENCES service_categories(shop_id, id) ON DELETE RESTRICT') THEN RAISE EXCEPTION 'translation FK drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.services'::regclass AND contype='f' AND confrelid='public.service_categories'::regclass AND confdeltype='r' AND pg_get_constraintdef(oid)='FOREIGN KEY (shop_id, category_id) REFERENCES service_categories(shop_id, id) ON DELETE RESTRICT') THEN RAISE EXCEPTION 'service category FK drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.service_category_translations'::regclass AND contype='c' AND pg_get_constraintdef(oid) LIKE '%zh-CN%' AND pg_get_constraintdef(oid) LIKE '%en%') THEN RAISE EXCEPTION 'locale check drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.service_categories'::regclass AND contype='c' AND pg_get_constraintdef(oid) LIKE '%btrim(canonical_name)%') THEN RAISE EXCEPTION 'canonical name check drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.service_categories'::regclass AND contype='c' AND pg_get_constraintdef(oid) LIKE '%sort_order >= 0%') THEN RAISE EXCEPTION 'sort order check drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.service_category_translations'::regclass AND contype='c' AND pg_get_constraintdef(oid) LIKE '%btrim(name)%') THEN RAISE EXCEPTION 'translation name check drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='service_categories_shop_active_sort_idx' AND indexdef LIKE '%(shop_id, is_active, sort_order, id)%') THEN RAISE EXCEPTION 'category index drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='service_category_translations_shop_locale_category_idx' AND indexdef LIKE '%(shop_id, locale, category_id)%') THEN RAISE EXCEPTION 'translation index drift'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='services_shop_category_idx' AND indexdef LIKE '%(shop_id, category_id)%') THEN RAISE EXCEPTION 'service category index drift'; END IF;
 SELECT count(*) INTO bad FROM service_categories c LEFT JOIN shops s ON s.id=c.shop_id WHERE s.id IS NULL; IF bad>0 THEN RAISE EXCEPTION 'category orphan: %',bad; END IF;
 SELECT count(*) INTO bad FROM service_category_translations t LEFT JOIN service_categories c ON c.shop_id=t.shop_id AND c.id=t.category_id WHERE c.id IS NULL; IF bad>0 THEN RAISE EXCEPTION 'translation orphan: %',bad; END IF;
 SELECT count(*) INTO bad FROM services s LEFT JOIN service_categories c ON c.shop_id=s.shop_id AND c.id=s.category_id WHERE s.category_id IS NOT NULL AND c.id IS NULL; IF bad>0 THEN RAISE EXCEPTION 'service category orphan: %',bad; END IF;
 SELECT count(*) INTO bad FROM service_category_translations t JOIN service_categories c ON c.id=t.category_id WHERE c.shop_id<>t.shop_id; IF bad>0 THEN RAISE EXCEPTION 'translation cross-tenant: %',bad; END IF;
 SELECT count(*) INTO bad FROM services s JOIN service_categories c ON c.id=s.category_id WHERE c.shop_id<>s.shop_id; IF bad>0 THEN RAISE EXCEPTION 'service cross-tenant: %',bad; END IF;
 SELECT count(*) INTO bad FROM (SELECT shop_id,category_id,locale FROM service_category_translations GROUP BY 1,2,3 HAVING count(*)>1) d; IF bad>0 THEN RAISE EXCEPTION 'duplicate translations: %',bad; END IF;
 SELECT count(*) INTO bad FROM service_category_translations WHERE locale NOT IN('zh-CN','en'); IF bad>0 THEN RAISE EXCEPTION 'invalid locale: %',bad; END IF;
END $$;
SELECT (SELECT count(*) FROM service_categories) category_count,
 (SELECT count(*) FROM service_category_translations) translation_count,
 (SELECT count(*) FROM services WHERE category_id IS NOT NULL) linked_service_count,
 (SELECT count(*) FROM services WHERE category_id IS NULL) remaining_unmapped_count,
 (SELECT count(*) FROM services WHERE category IS NULL) legacy_null_count,
 (SELECT count(*) FROM services WHERE category IS NOT NULL AND btrim(category)='') legacy_blank_count;
ROLLBACK;
